apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recommend
  namespace: default
spec:
  chart:
    spec:
      chart: ./recommend
      sourceRef:
        kind: GitRepository
        name: helm-config
  interval: 1m
  values:
    replicaCount: 2
    image:
      repository: andychoi1997/recommend-system
      tag: v1.0.0
