apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  # Open API
  OPENAI_API_KEY: c2stcHJvai1GcG1CZk5uTGRnbGdzV0lZWGwtNGhEUkFkTndVeHRnMXM3R3lRTjgtQzNocUZBc3JKZnF1aUpKUkFVOUItME12aTlTVjFvMHZrZ1QzQmxia0ZKWDhmQl9kWkRIcV9ULWMzMTNESDhEYk9RUGlaUER5dzhhSzliS3JQOWRENFpiYm15SWp5ZzRMTTVZajhlWU9neTdLSXlSUllPSUE=
  SQLALCHEMY_DATABASE_URL: bXlzcWwrcHlteXNxbDovL3Jvb3Q6cGxhbnRpZnlAZnVuZGluZy1teXNxbDozMzA2L2Z1bmRpbmctZGI=