apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGxhbnRpZnk=
  MYSQL_DATABASE: dXNlci1kYg==
  SPRING_DATASOURCE_URL: amRiYzpteXNxbDovL2F1dGgtbXlzcWw6MzMwNi91c2VyLWRi
  SPRING_DATASOURCE_PASSWORD: cGxhbnRpZnk=
  # Jasypt
  JASYPT_PASSWORD: SEtUT1NTUExBTlRJRlk=
  # OAuth
  OAUTH_KAKAO_CLIENT_ID: ZjViYmY5ZTJjZDFmNmJiMDVlODhjMmZkYTkwMjYwYjc=
  OAUTH_KAKAO_CLIENT_SECRET: S1lJVUY4ck1yMU9pbWQxRGdqa2NGcEF4aGpYOUNvcks=
  OAUTH_KAKAO_REDIRECT_URI: aHR0cDovL2s4cy1wbGFudGlmeS00YjA1MzI4ODAxLTEwMjcwNjE5ODQuYXAtbm9ydGhlYXN0LTEuZWxiLmFtYXpvbmF3cy5jb20vdjEvYXV0aA==
  # JWT
  JWT_SECRET: V2drU3RrMUNWcXZoK1NiazFnSUxFN0JKdG81YTJBSkpkK1ZWeXdMdUpSUT0=
  JWT_ACCESS_TOKEN_EXPIRATION: MzAwMDAw
  JWT_REFRESH_TOKEN_EXPIRATION: ODY0MDAwMDA=
  AUTH_SERVICE_URL: YXV0aC1zZXJ2aWNlOjgwODA=