apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: recommend-image-policy
  namespace: flux-system
spec:
  filterTags:
    pattern: '^latest$'
  policy:
    semver:
      range: '*'
