apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: card-service-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: card-service
  filterTags:
    pattern: ^.*$
  policy:
    alphabetical:
      order: desc  # 가장 최신 태그 선택
