apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: card-service-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: card-service
  filterTags:
    pattern: '^\d+$'  # 숫자만 포함된 태그 (예: 43, 44, 45)
  policy:
    numerical:
      order: asc  # 최신 숫자 태그 선택
