apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: card-mysql-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: card-mysql
  filterTags:
    pattern: latest
  policy:
    alphabetical:
      order: desc  # 가장 최신 태그 선택
