apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: card-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: card-image-repo
  filterTags:
    pattern: '^(latest|[0-9]+)$'
  policy:
    semver:
      range: "*"
