apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: chatbot-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: chatbot
  filterTags:
    pattern: ^.*$
  policy:
    alphabetical:
      order: asc  # 가장 최신 태그 선택