apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: recommend-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: recommend-image-repo  # 참조할 ImageRepository의 이름
  filterTags:
    pattern: '^(latest|[0-9]+)$'  # 숫자 태그와 latest 모두 감지
  policy:
    semver:
      range: '*'
