apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: helm-repo
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/hk-plantify/helm.git  # SSH URL
  secretRef:
    name: flux-system
