apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base
resources:
  - helm-releases/recommend-helmrelease.yaml
  - imagerepositories/recommend-imagerepository.yaml
  - imagepolicies/recommend-imagepolicy.yaml