apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helm-releases/          # 디렉터리에 kustomization.yaml이 있어야 함
  - ./imagepolicies/          # 디렉터리에 kustomization.yaml이 있어야 함
  - ./imagerepositories/      # 디렉터리에 kustomization.yaml이 있어야 함
  - ./imageupdateautomation/  # 디렉터리에 kustomization.yaml이 있어야 함
