apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base
resources:
  - helm-releases/chat-helmrelease.yaml
  - imagerepositories/chat-imagerepository.yaml
  - imagepolicies/chat-imagepolicy.yaml

  - helm-releases/card-helmrelease.yaml
  - imagerepositories/card-imagerepository.yaml
  - imagepolicies/card-imagepolicy.yaml

  - helm-releases/recommend-helmrelease.yaml
  - imagerepositories/recommend-imagerepository.yaml
  - imagepolicies/recommend-imagepolicy.yaml