apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helm-releases/
  - ./imagepolicies/
  - ./imagerepositories/
  - ./imageupdateautomation/

images:
  - name: andychoi1997/recommend-system
    newTag: "202412161012-f202e45d"  # ImageUpdateAutomation이 이 값을 최신 태그로 업데이트
