apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: base
  namespace: flux-system
spec:
  interval: 5m
  path: ./flux/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: helm-repo
