apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recommend
  namespace: default
spec:
  chart:
    spec:
      chart: ./helm/recommend # Helm 차트 경로
  interval: 5m
  values:
    replicaCount: 2
    image:
      repository: andychoi1997/recommend-system
      tag: v1.0.0
