apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  USERNAME: cm9vdA==
  PASSWORD: cGxhbnRpZnk=
  HOST: Y2FyZC1teXNxbA==
  PORT: MzMwNg==
  DBNAME: Y2FyZC1kYg==
  AUTH_SERVICE_URL: aHR0cDovL2F1dGgtc2VydmljZS5hdXRoLnN2Yzo4MDgw
  MYSQL_ROOT_PASSWORD: cGxhbnRpZnk=