apiVersion: v1
kind: Service
metadata:
  name: {{ include "model.fullname" . }}
  labels:
    {{- include "model.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "model.selectorLabels" . | nindent 4 }}
