apiVersion: v1
kind: Service
metadata:
  name: {{ include "model.fullname" . }}
  labels:
    {{- include "model.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 50052
      targetPort: 50052
      protocol: TCP
      name: grpc
  selector:
    {{- include "model.selectorLabels" . | nindent 4 }}
