apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: card
  namespace: card
spec:
  interval: 1m
  chart:
    spec:
      chart: ./card/charts/model
      sourceRef:
        kind: GitRepository
        name: helm-repo
        namespace: flux-system
  values:
    image:
      repository: andychoi1997/card-service
      tag: "{{ .Values.image.tag | default 'latest' }}" # ImagePolicy로부터 가져온 태그
