apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: card
  namespace: card
spec:
  releaseName: card
  chart:
    spec:
      chart: ./card/charts/model
      sourceRef:
        kind: GitRepository
        name: helm-repo
        namespace: flux-system
  interval: 5m
  values:
    image:
      repository: andychoi1997/card-service
      tag: latest