apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: card
  namespace: card
spec:
  releaseName: card
  chart:
    spec:
      chart: ./card/charts/mysql
      sourceRef:
        kind: GitRepository
        name: helm-repo
        namespace: flux-system
  interval: 5m
  values:
    image:
      repository: mysql
      tag: latest