apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chat-service
  namespace: chat
spec:
  releaseName: chat-service
  chart:
    spec:
      chart: ./chat/charts/service
      sourceRef:
        kind: GitRepository
        name: helm-repo
        namespace: flux-system
  interval: 5m
  values:
    image:
      repository: seungjusuh/chat-service
      tag: latest  # 고정된 'latest' 대신 ImagePolicy가 업데이트한 태그로 교체
