apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recommend
  namespace: recommend
spec:
  releaseName: recommend
  chart:
    spec:
      chart: ./recommend/charts/model
      sourceRef:
        kind: GitRepository
        name: helm-repo
        namespace: flux-system
  interval: 5m
  values:
    image:
      repository: andychoi1997/recommend-system
      tag: "{{ .Values.image.tag | default 'latest' }}"