apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recommend
  namespace: recommend
spec:
  releaseName: recommend
  chart:
    spec:
      chart: recommend/charts/model
      sourceRef:
        kind: GitRepository
        name: helm-repo
        namespace: flux-system
  interval: 5m
  values:
    image:
      repository: andychoi1997/recommend-system
      tag: "202412140830-dcd09ba0"