apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: base
  namespace: flux-system
spec:
  interval: 5m
  path: flux/base                 # base 디렉터리 내 kustomization.yaml 감시
  prune: true
  sourceRef:
    kind: GitRepository
    name: helm-repo
  timeout: 5m
