apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: recommend-image-automation
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: helm-repo
  update:
    path: ./recommend/charts/model/values.yaml
    strategy:
      kind: Setters
